import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UI } from "@components/UI";
import { readFile } from "fs/promises";
import { ProjectData } from "@lib";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const file = await readFile(
    process.cwd() + "/src/data/projects.json",
    "utf-8"
  );
  const projectData: ProjectData[] = JSON.parse(file);

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col">
          <UI projectData={projectData}>{children}</UI>
        </main>
      </body>
    </html>
  );
}
