import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UI } from "@components/UI";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col">
          <UI>{children}</UI>
        </main>
      </body>
    </html>
  );
}
